In [15]:
import pandas as pd
import glob as gl
import seaborn as sns

In [2]:
listed2401 = pd.read_csv("datasets/CRMLSListing202401.csv")

listed2401.head()

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,NaN,NaN,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road

In [3]:
listed2402 = pd.read_csv("datasets/CRMLSListing202401.csv")
listed2402.info()

<class 'pandas.DataFrame'>
RangeIndex: 27454 entries, 0 to 27453
Data columns (total 84 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   OriginalListPrice             27349 non-null  float64
 1   ListingKey                    27454 non-null  int64
 2   ListAgentEmail                27421 non-null  str
 3   CloseDate                     20136 non-null  str
 4   ClosePrice                    20001 non-null  float64
 5   ListAgentFirstName            27292 non-null  str
 6   ListAgentLastName             27451 non-null  str
 7   Latitude                      22233 non-null  float64
 8   Longitude                     22271 non-null  float64
 9   UnparsedAddress               27393 non-null  str
 10  PropertyType                  27454 non-null  str
 11  LivingArea                    23743 non-null  float64
 12  ListPrice                     27381 non-null  float64
 13  DaysOnMarket                  27454 non-null  int64
 14  ListOfficeName                27454 non-null  str
 15  BuyerOfficeName               19806 non-null  str
 16  CoListOfficeName              5640 non-null   str
 17  ListAgentFullName             27450 non-null  str
 18  CoListAgentFirstName          5591 non-null   str
 19  CoListAgentLastName           5602 non-null   str
 20  BuyerAgentMlsId               20057 non-null  str
 21  BuyerAgentFirstName           19985 non-null  str
 22  BuyerAgentLastName            20080 non-null  str
 23  FireplacesTotal               0 non-null      float64
 24  AssociationFeeFrequency       7831 non-null   str
 25  AboveGradeFinishedArea        0 non-null      float64
 26  ListingKeyNumeric             27454 non-null  int64
 27  MLSAreaMajor                  24798 non-null  str
 28  TaxAnnualAmount               219 non-null    float64
 29  CountyOrParish                27454 non-null  str
 30  PropertyType.1                27454 non-null  str
 31  MlsStatus                     27454 non-null  str
 32  ElementarySchool              2616 non-null   str
 33  ListAgentFirstName.1          27292 non-null  str
 34  AttachedGarageYN              18072 non-null  object
 35  ParkingTotal                  25408 non-null  float64
 36  BuilderName                   950 non-null    str
 37  PropertySubType               23689 non-null  str
 38  LotSizeAcres                  24588 non-null  float64
 39  SubdivisionName               9144 non-null   str
 40  BuyerOfficeAOR                19485 non-null  str
 41  YearBuilt                     24912 non-null  float64
 42  DaysOnMarket.1                27454 non-null  int64
 43  BuyerAgencyCompensationType   27435 non-null  str
 44  StreetNumberNumeric           27333 non-null  float64
 45  LivingArea.1                  23743 non-null  float64
 46  ListingId                     27454 non-null  str
 47  BathroomsTotalInteger         24913 non-null  float64
 48  City                          27408 non-null  str
 49  BuyerAgencyCompensation       27415 non-null  float64
 50  TaxYear                       37 non-null     float64
 51  BuildingAreaTotal             4168 non-null   float64
 52  BedroomsTotal                 23857 non-null  float64
 53  ContractStatusChangeDate      27314 non-null  str
 54  Longitude.1                   22271 non-null  float64
 55  ElementarySchoolDistrict      0 non-null      float64
 56  CoBuyerAgentFirstName         1669 non-null   str
 57  PurchaseContractDate          21281 non-null  str
 58  ListingContractDate           27454 non-null  str
 59  BelowGradeFinishedArea        72 non-null     float64
 60  BusinessType                  227 non-null    str
 61  Latitude.1                    22233 non-null  float64
 62  ListPrice.1                   27381 non-null  float64
 63  StateOrProvince               27452 non-null  str
 64  CoveredSpaces                 0 non-null      float64
 65  MiddleOrJuniorSchool          2662 non-null   str
 66  FireplaceYN                   23126 non-null  object
 67  Stories                       20230 non-null  float64
 68  HighSchool                    3459 non-null   str
 69  Levels                        21929 non-null  str
 70  ListAgentLastName.1           27451 non-null  str
 71  CloseDate.1                   20136 non-null  str
 72  LotSizeDimensions             1507 non-null   str
 73  LotSizeArea                   24701 non-null  float64
 74  MainLevelBedrooms             12990 non-null  float64
 75  NewConstructionYN             23627 non-null  object
 76  GarageSpaces                  22053 non-null  float64
 77  HighSchoolDistrict            16671 non-null  str
 78  PostalCode                    27444 non-null  str
 79  BuyerOfficeName.1             19806 non-null  str
 80  AssociationFee                18889 non-null  float64
 81  LotSizeSquareFeet             24659 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null      float64
 83  UnparsedAddress.1             27393 non-null  str
dtypes: float64(32), int64(4), object(3), str(45)
memory usage: 17.6+ MB

In [4]:
listed_files = sorted(gl.glob("datasets/CRMLSListing*.csv"))
df = pd.concat([pd.read_csv(f, low_memory=False) for f in listed_files], ignore_index=True)

df.shape

(853413, 84)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 853413 entries, 0 to 853412
Data columns (total 84 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             850101 non-null  float64
 1   ListingKey                    853413 non-null  int64
 2   ListAgentEmail                780379 non-null  str
 3   CloseDate                     258103 non-null  str
 4   ClosePrice                    235487 non-null  float64
 5   ListAgentFirstName            848406 non-null  str
 6   ListAgentLastName             853337 non-null  str
 7   Latitude                      741479 non-null  float64
 8   Longitude                     742183 non-null  float64
 9   UnparsedAddress               851262 non-null  str
 10  PropertyType                  853413 non-null  str
 11  LivingArea                    746971 non-null  float64
 12  ListPrice                     851278 non-null  float64
 13  DaysOnMarket                  853413 non-null  int64
 14  ListOfficeName                853413 non-null  str
 15  BuyerOfficeName               247757 non-null  str
 16  CoListOfficeName              170928 non-null  str
 17  ListAgentFullName             853185 non-null  str
 18  CoListAgentFirstName          170299 non-null  str
 19  CoListAgentLastName           170786 non-null  str
 20  BuyerAgentMlsId               249361 non-null  str
 21  BuyerAgentFirstName           249195 non-null  str
 22  BuyerAgentLastName            250117 non-null  str
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       246278 non-null  str
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             853413 non-null  int64
 27  MLSAreaMajor                  757063 non-null  str
 28  TaxAnnualAmount               6086 non-null    float64
 29  CountyOrParish                853412 non-null  str
 30  PropertyType.1                853413 non-null  str
 31  MlsStatus                     853413 non-null  str
 32  ElementarySchool              79286 non-null   str
 33  ListAgentFirstName.1          848406 non-null  str
 34  AttachedGarageYN              562479 non-null  object
 35  ParkingTotal                  801062 non-null  float64
 36  BuilderName                   29294 non-null   str
 37  PropertySubType               749275 non-null  str
 38  LotSizeAcres                  771905 non-null  float64
 39  SubdivisionName               285029 non-null  str
 40  BuyerOfficeAOR                235759 non-null  str
 41  YearBuilt                     783960 non-null  float64
 42  DaysOnMarket.1                853413 non-null  int64
 43  BuyerAgencyCompensationType   123538 non-null  str
 44  StreetNumberNumeric           849648 non-null  float64
 45  LivingArea.1                  746971 non-null  float64
 46  ListingId                     853413 non-null  str
 47  BathroomsTotalInteger         783481 non-null  float64
 48  City                          852453 non-null  str
 49  BuyerAgencyCompensation       123519 non-null  float64
 50  TaxYear                       868 non-null     float64
 51  BuildingAreaTotal             136801 non-null  float64
 52  BedroomsTotal                 750359 non-null  float64
 53  ContractStatusChangeDate      846541 non-null  str
 54  Longitude.1                   742183 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         19916 non-null   str
 57  PurchaseContractDate          369777 non-null  str
 58  ListingContractDate           853413 non-null  str
 59  BelowGradeFinishedArea        3422 non-null    float64
 60  BusinessType                  5979 non-null    str
 61  Latitude.1                    741479 non-null  float64
 62  ListPrice.1                   851278 non-null  float64
 63  StateOrProvince               853347 non-null  str
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          79378 non-null   str
 66  FireplaceYN                   730903 non-null  object
 67  Stories                       632176 non-null  float64
 68  HighSchool                    104334 non-null  str
 69  Levels                        689561 non-null  str
 70  ListAgentLastName.1           853337 non-null  str
 71  CloseDate.1                   258103 non-null  str
 72  LotSizeDimensions             48685 non-null   str
 73  LotSizeArea                   775684 non-null  float64
 74  MainLevelBedrooms             394847 non-null  float64
 75  NewConstructionYN             738704 non-null  object
 76  GarageSpaces                  691399 non-null  float64
 77  HighSchoolDistrict            514192 non-null  str
 78  PostalCode                    853205 non-null  str
 79  BuyerOfficeName.1             247757 non-null  str
 80  AssociationFee                577730 non-null  float64
 81  LotSizeSquareFeet             774608 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             851262 non-null  str
dtypes: float64(32), int64(4), object(3), str(45)
memory usage: 546.9+ MB

In [23]:
dot1_cols = [col for col in df.columns if col.endswith(".1")]
dot1_cols

['PropertyType.1',
 'ListAgentFirstName.1',
 'DaysOnMarket.1',
 'LivingArea.1',
 'Longitude.1',
 'Latitude.1',
 'ListPrice.1',
 'ListAgentLastName.1',
 'CloseDate.1',
 'BuyerOfficeName.1',
 'UnparsedAddress.1']

In [30]:
df[(~df["UnparsedAddress"].isna() | ~df["UnparsedAddress.1"].isna()) &\
    (df["UnparsedAddress"] != df["UnparsedAddress.1"])][["UnparsedAddress","UnparsedAddress.1"]].head()

Empty DataFrame
Columns: [UnparsedAddress, UnparsedAddress.1]
Index: []

In [21]:
df[(~df["CloseDate"].isna() | ~df["CloseDate.1"].isna()) &\
    (df["CloseDate"] != df["CloseDate.1"])][["CloseDate","CloseDate.1"]].head()

Empty DataFrame
Columns: [CloseDate, CloseDate.1]
Index: []

In [ ]:
# DELETE THE DOT1 COLUMNS

In [9]:
# don't run this
#df_test = pd.DataFrame()

#for file in listed_files:
#    list_df = pd.read_csv(file, low_memory=False)
#    print(f"Loaded {list_df.shape[0]} rows from {file}")
#    df_test = pd.concat([df_test, list_df], ignore_index=True)

In [34]:
df["PropertyType"].unique()

<StringArray>
[ 'ManufacturedInPark',      'CommercialSale',         'Residential',
    'ResidentialLease',                'Land',   'ResidentialIncome',
     'CommercialLease', 'BusinessOpportunity']
Length: 8, dtype: str

In [17]:
df = df[df["PropertyType"] == "Residential"]

df.shape

(540391, 84)

In [18]:
df_null_cnt = (round(df.isnull().sum() / df.shape[0] * 100, 2)).reset_index()
df_null_cnt.columns = ["ColName", "NullPct"]
df_null_cnt.head()

             ColName  NullPct
0  OriginalListPrice     0.14
1         ListingKey     0.00
2     ListAgentEmail     8.74
3          CloseDate    69.75
4         ClosePrice    73.50

In [20]:
df_null_cnt["isSparse"] = df_null_cnt["NullPct"] >= 90.0
df_null_cnt

                         ColName  NullPct  isSparse
0              OriginalListPrice     0.14     False
1                     ListingKey     0.00     False
2                 ListAgentEmail     8.74     False
3                      CloseDate    69.75     False
4                     ClosePrice    73.50     False
..                           ...      ...       ...
79             BuyerOfficeName.1    71.39     False
80                AssociationFee    24.05     False
81             LotSizeSquareFeet     8.12     False
82  MiddleOrJuniorSchoolDistrict   100.00      True
83             UnparsedAddress.1     0.13     False

[84 rows x 3 columns]

In [22]:
date_cols = [col for col in df.columns if "date" in col.lower()]
date_cols

['CloseDate',
 'ContractStatusChangeDate',
 'PurchaseContractDate',
 'ListingContractDate',
 'CloseDate.1']

In [23]:
df_null_cnt[df_null_cnt.ColName.isin(date_cols)].head()

                     ColName  NullPct  isSparse
3                  CloseDate    69.75     False
53  ContractStatusChangeDate     1.12     False
57      PurchaseContractDate    51.09     False
58       ListingContractDate     0.00     False
71               CloseDate.1    69.75     False

In [37]:
num_cols = ["ListPrice", "ClosePrice", "LivingArea", "BedroomsTotal", "BathroomsTotalInteger", "Latitude", "Longitude"]
df[num_cols].head()

,ListPrice,ClosePrice,LivingArea,BedroomsTotal,BathroomsTotalInteger,Latitude,Longitude
0,90000.0,NaN,960.0,4.0,1.0,34.097939,-117.909653
1,1500000.0,NaN,NaN,NaN,0.0,33.121241,-117.081614
2,1340000.0,NaN,1301.0,2.0,2.0,34.052207,-118.408445
3,2500000.0,NaN,2788.0,4.0,3.0,33.496363,-117.691677
4,3150000.0,NaN,3250.0,6.0,4.0,34.119345,-118.111254

In [26]:
df_null_cnt[df_null_cnt.ColName.isin(num_cols)]

                  ColName  NullPct  isSparse
4              ClosePrice    73.50     False
7                Latitude    14.83     False
8               Longitude    14.83     False
11             LivingArea     0.10     False
12              ListPrice     0.00     False
47  BathroomsTotalInteger     0.01     False
52          BedroomsTotal     0.03     False

In [32]:
sold_files = sorted(gl.glob("datasets/CRMLSSold*.csv"))
df_sold = pd.concat([pd.read_csv(f, low_memory=False) for f in sold_files], ignore_index=True)

In [33]:
dot1_cols = [col for col in df_sold.columns if col.endswith(".1")]
dot1_cols

[]

In [28]:
df_null_cnt2 = (round(df_sold.isnull().sum() / df_sold.shape[0] * 100, 2)).reset_index()
df_null_cnt2.columns = ["ColName", "NullPct"]
df_null_cnt2["isSparse"] = df_null_cnt2["NullPct"] >= 90.0
df_null_cnt2.head()

         ColName  NullPct  isSparse
0  BuyerAgentAOR    12.10     False
1   ListAgentAOR    11.51     False
2       Flooring    41.22     False
3         ViewYN    10.02     False
4   WaterfrontYN    99.95      True

In [29]:
df_null_cnt2[df_null_cnt2.ColName.isin(date_cols)]

                     ColName  NullPct  isSparse
10                 CloseDate     0.00     False
54  ContractStatusChangeDate     0.12     False
57      PurchaseContractDate     2.00     False
58       ListingContractDate     0.01     False

In [31]:
df_null_cnt2[df_null_cnt2.ColName.isin(num_cols)]

                  ColName  NullPct  isSparse
11             ClosePrice     0.00     False
14               Latitude     3.22     False
15              Longitude     3.19     False
18             LivingArea     7.06     False
19              ListPrice     0.15     False
49  BathroomsTotalInteger     4.64     False
53          BedroomsTotal     6.66     False

In [56]:
(df["ListingKey"].value_counts() > 1).head()

ListingKey
1076131624    True
1079186253    True
1104326441    True
1078833366    True
1076393700    True
Name: count, dtype: bool

In [57]:
df[df["ListingKey"] == 1079186253]

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
264744,4600.0,1079186253,bakdache@sbcglobal.net,NaN,NaN,Talal,Bakdache,32.982086,-117.272519,190 Del Mar Shores 59,...,NaN,NaN,1.0,Solana Beach,92075,NaN,750.0,261360.0,NaN,190 Del Mar Shores 59
339359,4600.0,1079186253,bakdache@sbcglobal.net,NaN,NaN,Talal,Bakdache,32.982086,-117.272519,190 Del Mar Shores 59,...,NaN,NaN,1.0,Solana Beach,92075,NaN,750.0,261360.0,NaN,190 Del Mar Shores 59
383918,4600.0,1079186253,bakdache@sbcglobal.net,NaN,NaN,Talal,Bakdache,32.982086,-117.272519,190 Del Mar Shores 59,...,NaN,NaN,1.0,Solana Beach,92075,NaN,750.0,261360.0,NaN,190 Del Mar Shores 59
493860,4600.0,1079186253,bakdache@sbcglobal.net,NaN,NaN,Talal,Bakdache,32.982086,-117.272519,190 Del Mar Shores 59,...,NaN,NaN,1.0,Solana Beach,92075,NaN,750.0,261360.0,NaN,190 Del Mar Shores 59